services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_operacoes
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: operacoes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - operacoes_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d operacoes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  spring:
    build:
      context: ../backend-spring
      dockerfile: ../docker/Dockerfile-spring
    container_name: spring_operacoes
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/operacoes_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - operacoes_net

  angular:
    build:
      context: ../frontend-angular
      dockerfile: ../docker/Dockerfile-angular
    container_name: angular_operacoes
    ports:
      - "4200:4200"
    volumes:
      - ../frontend-angular:/app
      - /app/node_modules
    depends_on:
      - spring
    networks:
      - operacoes_net

networks:
  operacoes_net:

volumes:
  postgres_data: